import json
from collections import defaultdict


def find_journal_with_most_drugs(json_path):
    """finds th journal with the most different drug mentions
        counts the unique drugs mentioned for each journal and
        identify the journal with the highest count

        Parameters:
        json_path: path of the json file generated by the data pipeline

        Returns:
        max_journal : the journal mentioning the most different drugs
        drug_count: the number of the different drugs
        """

    drug_mentions = json.load(open(json_path))
    journal_counts = defaultdict(set)
    for drug, mentions in drug_mentions.items():
        for mention in mentions:
            journal = mention['journal']
            journal_counts[journal].add(drug)

    # Find the journal with the most different drugs mentioned
    max_journal = max(journal_counts, key=lambda x: len(journal_counts[x]))
    return max_journal, len(journal_counts[max_journal])


def main():
    max_journal, drug_count = find_journal_with_most_drugs('data/graph.json')
    print(f"The journal mentioning the most different drugs is '{max_journal}' "
          f"with {drug_count} different drugs mentioned.")


if __name__ == "__main__":
    main()
